name: Check build ready
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      contents: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            **Packages building :raacing_car:**
          message-success: |
            **Build Success :white_check_mark:**
          message-failure: |
            **Build failed :no_entry_sign:**
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # Defaults to the user or organization that owns the workflow file
      - run: npm ci
      # set new version
      - name: Build
        id: build-step
        run: npm run build
    #   - name: Build failed message
    #     if: failure()
    #     uses: mshick/add-pr-comment@v2
    #     with:
    #       update-only: true
    #       message: |
    #         **Packages building :raacing_car:**
    #       message-success: |
    #         **Build Success :white_check_mark:**
