name: Check build ready
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      contents: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: mshick/add-pr-comment@v2
        with:
          refresh-message-position: true
          message: |
            **Packages building :racing_car:**
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # Defaults to the user or organization that owns the workflow file
      - run: npm ci
      # set new version
      - name: Build
        id: build-step
        run: |
          npm run build || (npm run build >> output.log && echo "message=$(cat output.log)" >> $GITHUB_OUTPUT)
      - name: Build failed message
        if: failure()
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            **Package build failed :no_entry_sign:**
            Output:
            ```
            ${{steps.build-step.outputs.message}}
            ```
          refresh-message-position: true
          update-only: true
      - name: Build Success message
        if: success()
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            **Package build Success :white_check_mark:**
          refresh-message-position: true
          update-only: true
