name: Check build ready
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      contents: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: mshick/add-pr-comment@v2
        with:
          refresh-message-position: true
          message: |
            **Packages building :racing_car:**
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # Defaults to the user or organization that owns the workflow file
      - run: npm ci
      # set new version
      - name: Build
        id: build-step
        run: npm run build
      - name: Build failed message
        id: set-fail-message
        if: failure()
        run: echo "result=$(npm run build)" >> output.log
      - name: Read package.json
        id: fail-message
        uses: juliangruber/read-file-action@v1
        with:
          path: ./output.log
      - name: Build failed message
        if: always()
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ** Package build failed **
            Reasons:
            ```
            ${{steps.fail-message.outputs.content}}
            ```
          refresh-message-position: true
          update-only: true
