name: Check build ready
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      contents: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: mshick/add-pr-comment@v2
        with:
          update-only: true
          message: |
            **Packages building :raacing_car:**
          message-success: |
            **Build Success :white_check_mark:**
          message-failure: |
            **Build Failed :no_entry_sign:**
            Please check log below:
            ```
            << FILE_CONTENTS >>
            ```
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # Defaults to the user or organization that owns the workflow file
      - run: npm ci
      # set new version
      - name: Build
        run: npm run build | tee message.txt
